#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *entry = NULL;
	rt_entry_t *best_entry = NULL;
	u32 max_match = 0;

	list_for_each_entry(entry, &rtable, list) {
		if((dst & entry->mask) == (entry->dest & entry->mask)){
			u32 match = entry->mask;
			if(match > max_match){
				max_match = match;
				best_entry = entry;
			}
		}
	}
	return best_entry;
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to sendd the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	//log(DEBUG, "Sending IP packet");
	struct iphdr *ip = (struct iphdr *)packet;
	u32 dst = ntohl(ip->daddr);
	rt_entry_t *entry = longest_prefix_match(dst);
	if (entry == NULL) {
		//log(ERROR, "No route to host %s, sending ICMP DEST_UNREACH", NET_IP_FMT_STR(dst));
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		return;
	}
	iface_info_t *iface = entry->iface;
	ip->saddr = htonl(iface->ip);
	ip->checksum = ip_checksum(ip);

	char * new_packet = malloc(ETHER_HDR_SIZE + len);
	struct ether_header *eh = (struct ether_header *)new_packet;
	memcpy(eh->ether_shost, iface->mac, ETH_ALEN);
	eh->ether_type = htons(ETH_P_IP);

	memcpy(new_packet + ETHER_HDR_SIZE, packet, len);
	u32 nexthop = entry->gw ? entry->gw : dst;
	//log(DEBUG, "comfirm next hop %u", nexthop);
	iface_send_packet_by_arp(iface, nexthop, new_packet, len + ETHER_HDR_SIZE);

	//free(new_packet);
}
